### PR TITLE
Fixed incorrect portal selection & Rotate view roll leaving at 1 degree

### PR DESCRIPTION
**Pull request by Snailic**
Added a util function to get the closest portal hit given source pos and direction of vector, previously it was returning the first portal that was hit.
- wp.GetFirstPortalHit(source, direction)

### CODE REVIEW

**Comment by Snailic** [comment]
To clarify, previously if you had 2 portals inline with each other, the one that was placed first would be selected rather than the closest one by distance.

**Comment by MattJeanes** [comment]
Thanks for your pull request! Was it really that simple to fix the rotate 1 degree issue 🤦🏻‍♂️ - I was discussing this with @francodml just yesterday!

I've just pushed some small formatting improvements to your branch, and I'm going to give it a test in a moment, code looks good!

**Comment by MattJeanes** [comment]
After reading through the rotate view code properly I see where it was going wrong and fixed it properly now! I'm all happy with your changes in-game so merging this in, thanks!

**Review by MattJeanes — APPROVED** [review]

**Comment by MattJeanes** [comment]
This has now been deployed to the Doors addon on workshop, thanks for your contribution :)

**Pull request merged**
