### PR TITLE
Add SetPartner Input

### PR DESCRIPTION
**Pull request by WilhelmW**

### CODE REVIEW

**Comment by MattJeanes** [comment]
Hi there, thanks for your contribution - can you explain the purpose of this change? Looks related to dynamically changing portal targets from within hammer?

**Comment by WilhelmW** [comment]
The Change is that you can switch portal targets with logic at run time

**Comment by MattJeanes** [comment]
Looks good to me, thanks

**Comment by MattJeanes** [comment]
This change has been published to the Doors Steam Workshop addon: https://steamcommunity.com/sharedfiles/filedetails/changelog/499280258

**Pull request merged**
