### PR TITLE
Basic trace diversion

### PR DESCRIPTION
**Pull request by Snailic**
Detours traceline to account for portals

### CODE REVIEW

**Comment by Snailic** [comment]
Might need to look into the possibility of an infinite loop. Probably should add a cap to the number of times it can pass through.

**Comment by MattJeanes** [comment]
Very nice! Don't worry about effects at least in this PR - feel free to open another one after this one though. I agree, there needs to be protection against infinite loops but otherwise nice work!

**Comment by MattJeanes** [comment]
Actually that said it looks like the way you've implemented it already protects against an infinite loop scenario as you're not recursively calling itself, only calling the original func so should be fine - going to give it a test now

**Comment by MattJeanes** [comment]
I've made some changes to this locally, but first i'm going to merge this in - thanks for your contribution!

**Pull request merged**
